security: 
    ignore-cvss-severity-below: 0 
    ignore-cvss-unknown-severity: False 
    ignore-vulnerabilities: 
        71064:
            reason: pytest does not make use of this feature 
            expires: '2024-12-21'
    continue-on-vulnerability-error: False 